language: generic
sudo: required
  services:
    - docker

  before_install:
   - docker build -t jimoh9324/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true jimoh9324/docker-react npm run test
